# tests/stress/locust_stress_post_project.py
import csv
import random
import os
from locust import HttpUser, task, constant, events

# 全域變數儲存 Tokens
TOKENS = []
# 指定讀取雇主的 Token 檔案
TOKEN_FILE = "tokens_employer.csv"

# 1. 啟動時載入 Token
@events.init.add_listener
def _(environment, **kwargs):
    global TOKENS
    
    if not os.path.exists(TOKEN_FILE):
        print(f"❌ 錯誤: 找不到 {TOKEN_FILE}！")
        print("💡 請先執行: python generate_employer_tokens.py")
        environment.runner.quit()
        return

    try:
        with open(TOKEN_FILE, "r", encoding="utf-8") as f:
            reader = csv.reader(f)
            TOKENS = [row[0] for row in reader if row]
        print(f"✅ [Test 4] 已載入 {len(TOKENS)} 個雇主 Token。")
    except Exception as e:
        print(f"❌ 讀取 CSV 失敗: {e}")
        environment.runner.quit()

class WriteStressUser(HttpUser):
    # 設定每位使用者每秒發送 1 次請求
    # 寫入操作較重，保持 1 RPS 是合理的壓力
    wait_time = constant(1)
    
    access_token = None

    def on_start(self):
        # 隨機分配一個雇主身分
        if TOKENS:
            self.access_token = random.choice(TOKENS)
        else:
            self.stop()

    @task
    def create_project(self):
        """
        模擬雇主刊登案件 (Insert Operation)
        """
        if not self.access_token: return

        headers = {"Authorization": f"Bearer {self.access_token}"}
        
        # 產生隨機資料以模擬真實寫入
        random_id = random.randint(1, 100000)
        
        payload = {
            "title": f"Stress Test Project #{random_id}",
            "description": f"This is a stress test project generated by Locust. Random ID: {random_id}",
            "budget_min": 1000,
            "budget_max": 5000,
            "work_type": random.choice(["遠端", "實體", "混合"]),
            "location": random.choice(["台北", "台中", "高雄", "Remote"]),
            "skill_tag_ids": [] # 保持為空，專注測試 Projects 表的寫入
        }
        
        # 發送 POST 請求
        with self.client.post(
            "/projects/", 
            json=payload, 
            headers=headers, 
            name="/projects/ (Create Write)",
            catch_response=True,
            timeout=10 # 設定 10 秒逾時
        ) as response:
            
            if response.status_code == 201:
                response.success()
            elif response.status_code >= 500:
                # 500 通常代表 DB 連線池爆了或是 Deadlock
                response.failure(f"DB Error: {response.status_code} - {response.text}")
            elif response.status_code == 403:
                # 若這時還出現 403，代表 Token 生成有誤或權限驗證邏輯有問題
                response.failure(f"Permission Denied (Role Error): {response.status_code}")
            elif response.status_code == 401:
                response.failure("Unauthorized (Invalid Token)")
            else:
                response.failure(f"Failed: {response.status_code} - {response.text[:50]}")