"""Initial tables

Revision ID: 9842bada75e3
Revises: 
Create Date: 2025-11-29 18:38:49.422994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9842bada75e3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill_tags',
    sa.Column('tag_id', sa.CHAR(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('is_managed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('tag_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('user_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('自由工作者', '雇主', '系統管理員', name='userroleenum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('employer_profiles',
    sa.Column('profile_id', sa.CHAR(length=36), nullable=False),
    sa.Column('user_id', sa.CHAR(length=36), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('company_bio', sa.TEXT(), nullable=True),
    sa.Column('company_logo_url', sa.String(length=500), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('social_links', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_index(op.f('ix_employer_profiles_user_id'), 'employer_profiles', ['user_id'], unique=True)
    op.create_table('freelancer_profiles',
    sa.Column('profile_id', sa.CHAR(length=36), nullable=False),
    sa.Column('user_id', sa.CHAR(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('bio', sa.TEXT(), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('visibility', sa.Enum('公開', '僅受邀', '私人'), nullable=True),
    sa.Column('social_links', sa.JSON(), nullable=True),
    sa.Column('reputation_score', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_index(op.f('ix_freelancer_profiles_user_id'), 'freelancer_profiles', ['user_id'], unique=True)
    op.create_table('notifications',
    sa.Column('notification_id', sa.CHAR(length=36), nullable=False),
    sa.Column('user_id', sa.CHAR(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=True),
    sa.Column('link_url', sa.String(length=500), nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('projects',
    sa.Column('project_id', sa.CHAR(length=36), nullable=False),
    sa.Column('employer_id', sa.CHAR(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('status', sa.Enum('招募中', '已關閉', '已成案'), nullable=True),
    sa.Column('work_type', sa.Enum('遠端', '實體', '混合'), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('budget_min', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('budget_max', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('proposals_deadline', sa.TIMESTAMP(), nullable=True),
    sa.Column('completion_deadline', sa.TIMESTAMP(), nullable=True),
    sa.Column('required_people', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['employer_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_index(op.f('ix_projects_employer_id'), 'projects', ['employer_id'], unique=False)
    op.create_table('project_skill_tags',
    sa.Column('project_skill_tag_id', sa.CHAR(length=36), nullable=False),
    sa.Column('project_id', sa.CHAR(length=36), nullable=True),
    sa.Column('tag_id', sa.CHAR(length=36), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['skill_tags.tag_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_skill_tag_id')
    )
    op.create_index(op.f('ix_project_skill_tags_project_id'), 'project_skill_tags', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_skill_tags_tag_id'), 'project_skill_tags', ['tag_id'], unique=False)
    op.create_table('proposals',
    sa.Column('proposal_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('project_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('freelancer_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('brief_description', sa.Text(), nullable=True),
    sa.Column('attachment_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['freelancer_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('proposal_id')
    )
    op.create_index(op.f('ix_proposals_freelancer_id'), 'proposals', ['freelancer_id'], unique=False)
    op.create_index(op.f('ix_proposals_project_id'), 'proposals', ['project_id'], unique=False)
    op.create_table('user_skill_tags',
    sa.Column('user_skill_tag_id', sa.CHAR(length=36), nullable=False),
    sa.Column('profile_id', sa.CHAR(length=36), nullable=True),
    sa.Column('tag_id', sa.CHAR(length=36), nullable=True),
    sa.Column('familiarity_level', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['freelancer_profiles.profile_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['skill_tags.tag_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('user_skill_tag_id')
    )
    op.create_index(op.f('ix_user_skill_tags_profile_id'), 'user_skill_tags', ['profile_id'], unique=False)
    op.create_index(op.f('ix_user_skill_tags_tag_id'), 'user_skill_tags', ['tag_id'], unique=False)
    op.create_table('contracts',
    sa.Column('contract_id', sa.CHAR(length=36), nullable=False),
    sa.Column('project_id', sa.CHAR(length=36), nullable=False),
    sa.Column('proposal_id', sa.CHAR(length=36), nullable=False),
    sa.Column('employer_id', sa.CHAR(length=36), nullable=False),
    sa.Column('freelancer_id', sa.CHAR(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('start_date', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('end_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('status', sa.Enum('協商中', '進行中', '雇主請求修改', '工作者請求修改', '雇主請求終止', '工作者請求終止', '工作者要求驗收', '已完成', '終止', name='contract_status_enum'), nullable=False),
    sa.Column('version', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['employer_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['freelancer_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.proposal_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('contract_id')
    )
    op.create_index(op.f('ix_contracts_employer_id'), 'contracts', ['employer_id'], unique=False)
    op.create_index(op.f('ix_contracts_freelancer_id'), 'contracts', ['freelancer_id'], unique=False)
    op.create_index(op.f('ix_contracts_project_id'), 'contracts', ['project_id'], unique=False)
    op.create_index(op.f('ix_contracts_proposal_id'), 'contracts', ['proposal_id'], unique=True)
    op.create_table('chat_rooms',
    sa.Column('room_id', sa.CHAR(length=36), nullable=False),
    sa.Column('context_project_id', sa.CHAR(length=36), nullable=True),
    sa.Column('context_contract_id', sa.CHAR(length=36), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['context_contract_id'], ['contracts.contract_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['context_project_id'], ['projects.project_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('room_id')
    )
    op.create_index(op.f('ix_chat_rooms_context_contract_id'), 'chat_rooms', ['context_contract_id'], unique=False)
    op.create_index(op.f('ix_chat_rooms_context_project_id'), 'chat_rooms', ['context_project_id'], unique=False)
    op.create_table('deliverables',
    sa.Column('deliverable_id', sa.CHAR(length=36), nullable=False),
    sa.Column('contract_id', sa.CHAR(length=36), nullable=False),
    sa.Column('uploader_id', sa.CHAR(length=36), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('acceptance_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.contract_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('deliverable_id')
    )
    op.create_index(op.f('ix_deliverables_contract_id'), 'deliverables', ['contract_id'], unique=False)
    op.create_index(op.f('ix_deliverables_uploader_id'), 'deliverables', ['uploader_id'], unique=False)
    op.create_table('reviews',
    sa.Column('review_id', sa.CHAR(length=36), nullable=False),
    sa.Column('contract_id', sa.CHAR(length=36), nullable=False),
    sa.Column('reviewer_id', sa.CHAR(length=36), nullable=False),
    sa.Column('reviewee_id', sa.CHAR(length=36), nullable=False),
    sa.Column('rating_communication_fw', sa.DECIMAL(precision=2, scale=1), nullable=True),
    sa.Column('rating_professionalism_fw', sa.DECIMAL(precision=2, scale=1), nullable=True),
    sa.Column('rating_punctuality_fw', sa.DECIMAL(precision=2, scale=1), nullable=True),
    sa.Column('rating_quality_fw', sa.DECIMAL(precision=2, scale=1), nullable=True),
    sa.Column('rating_communication_we', sa.DECIMAL(precision=2, scale=1), nullable=True),
    sa.Column('rating_quality_we', sa.DECIMAL(precision=2, scale=1), nullable=True),
    sa.Column('rating_compensation_we', sa.DECIMAL(precision=2, scale=1), nullable=True),
    sa.Column('rating_process_we', sa.DECIMAL(precision=2, scale=1), nullable=True),
    sa.Column('comment', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.contract_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewee_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_index(op.f('ix_reviews_contract_id'), 'reviews', ['contract_id'], unique=False)
    op.create_index(op.f('ix_reviews_reviewee_id'), 'reviews', ['reviewee_id'], unique=False)
    op.create_index(op.f('ix_reviews_reviewer_id'), 'reviews', ['reviewer_id'], unique=False)
    op.create_table('chat_room_participants',
    sa.Column('participant_id', sa.CHAR(length=36), nullable=False),
    sa.Column('room_id', sa.CHAR(length=36), nullable=False),
    sa.Column('user_id', sa.CHAR(length=36), nullable=False),
    sa.Column('joined_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['chat_rooms.room_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('participant_id')
    )
    op.create_index(op.f('ix_chat_room_participants_room_id'), 'chat_room_participants', ['room_id'], unique=False)
    op.create_index(op.f('ix_chat_room_participants_user_id'), 'chat_room_participants', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('message_id', sa.CHAR(length=36), nullable=False),
    sa.Column('room_id', sa.CHAR(length=36), nullable=False),
    sa.Column('sender_id', sa.CHAR(length=36), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('attachment_url', sa.String(length=500), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['chat_rooms.room_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index(op.f('ix_messages_room_id'), 'messages', ['room_id'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_room_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_chat_room_participants_user_id'), table_name='chat_room_participants')
    op.drop_index(op.f('ix_chat_room_participants_room_id'), table_name='chat_room_participants')
    op.drop_table('chat_room_participants')
    op.drop_index(op.f('ix_reviews_reviewer_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_reviewee_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_contract_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_deliverables_uploader_id'), table_name='deliverables')
    op.drop_index(op.f('ix_deliverables_contract_id'), table_name='deliverables')
    op.drop_table('deliverables')
    op.drop_index(op.f('ix_chat_rooms_context_project_id'), table_name='chat_rooms')
    op.drop_index(op.f('ix_chat_rooms_context_contract_id'), table_name='chat_rooms')
    op.drop_table('chat_rooms')
    op.drop_index(op.f('ix_contracts_proposal_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_project_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_freelancer_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_employer_id'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_index(op.f('ix_user_skill_tags_tag_id'), table_name='user_skill_tags')
    op.drop_index(op.f('ix_user_skill_tags_profile_id'), table_name='user_skill_tags')
    op.drop_table('user_skill_tags')
    op.drop_index(op.f('ix_proposals_project_id'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_freelancer_id'), table_name='proposals')
    op.drop_table('proposals')
    op.drop_index(op.f('ix_project_skill_tags_tag_id'), table_name='project_skill_tags')
    op.drop_index(op.f('ix_project_skill_tags_project_id'), table_name='project_skill_tags')
    op.drop_table('project_skill_tags')
    op.drop_index(op.f('ix_projects_employer_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_freelancer_profiles_user_id'), table_name='freelancer_profiles')
    op.drop_table('freelancer_profiles')
    op.drop_index(op.f('ix_employer_profiles_user_id'), table_name='employer_profiles')
    op.drop_table('employer_profiles')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('skill_tags')
    # ### end Alembic commands ###
